name: Package API

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
    release:
      types:
        -created
jobs:
  build:
    name: Package
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0.103'
        source-url: https://nuget.pkg.github.com/AlexandreBrisebois/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: restore
      run: dotnet restore "./src/megaphone.api.sln"

    - name: build
      run: dotnet build "./src/megaphone.api.sln" --no-restore -c Release

    - name: package - megaphone.api
      run: dotnet publish "./src/megaphone.api/megaphone.api.csproj" -c Release --no-build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./src/megaphone.api/bin/Release/net5.0/publish/
        push: true
        file: ./src/Dockerfile
        tags: |
            ${{ format('{0}/api:latest',secrets.REGISTRY_URL) }}
            ${{ format('{0}/api:1.0.0-preview-{1}',secrets.REGISTRY_URL, github.run_number) }}